#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi

DESC="devbot"
DAEMON=/usr/bin/racket /home/retran/build-tools/devbot/devbot.rkt

start-stop-daemon --start --exec "$DAEMON"
